### ISSUE TITLE
Feature: SDRPlay RSP Tuner Support

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#52]
Add support for all RSP tuners (except RSP1 which is not supported by the sdrplay API)

# TODO
- [x] RSP Tuners hang on shutdown.  Deregistration of DiscoveredTunerModel as a TunerEvent listener is hanging because another thread is potentially broadcasting an event that is being put back onto the Swing event thread, causing the whole thing to lock.
- [x] RSPduo enable or disable should be restricted to tuner 1 and should automatically perform same op on tuner 2.
- [x] RSPduo, and maybe others, have frequency misalignment that requires a 435-440 ppm setting to offset
- [x] Disable and reenable of a discovered RSP tuner doesn't allow controlling the device.
- [ ] Allow user to specify SDRplay API library install location for non-default installations.
- [ ] Default RSP1A tuner configuration is not correctly updating sample rate to 8 MHz default on first-time use of software.

**Comment by n2cr** [comment]
Suggest that this enhancement be modified to add support for both SDRPlay RSP2 as well as RSP1.

**Comment by infecticide** [comment]
I've just recently purchased an RSP2Pro.    Is there anything a non-programmer can do to assist with this feature request?

**Comment by ImagoTrigger** [comment]
bump: https://github.com/SDRplay/examples/blob/master/play_sdr.c

**Comment by StaRipper** [comment]
Bump the beat

**Comment by LordDonkey** [comment]
I second this. I've been eyeing up the MSI.SDR. It has up to 10 MHz of bandwidth and would cover enough spectrum to fully cover the system I monitor. It uses the same drivers as the RSP1.

**Comment by StaRipper** [comment]
> 
> 
> Add support for RSP1 and RSP2 tuner

On v0.5.0 Alpha1  not recognizing Sdrplay RSP1

**Comment by StaRipper** [comment]
[https://forums.radioreference.com/threads/dsdplus-2-256-with-sdrplay-rsp1.409013/](url)

**Comment by NoahJaehnert** [comment]
Would love to see SDRPlay support added as well. I have an RSP2 that I'd like to use with sdrtrunk.

**Comment by dseven** [comment]
Came here trying to find out if I could use my RSPdx. The P25 system that I monitor spans about 4.5MHz - more than one R820T can cover without retuning, etc..... so add me to the wish list!

**Comment by liquidmayo** [comment]
adding another rsp1a to the list

**Comment by TheButterZone** [comment]
Add another RSP1.

**Comment by phipac** [comment]
For me, having RSP support would make this already fantastic package even more so!

**Comment by patomoi** [comment]
would be great that this software supports RSP family
